# Generated by Django 3.2.5 on 2023-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32, null=True)),
                ('pass_fail_num', models.IntegerField(default=0)),
                ('lock', models.BooleanField(default=False)),
                ('unlock_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
